#!/bin/bash -x
#SBATCH --account={accountname}
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --output=stylegan3_out.%j
#SBATCH --error=stylegan3_err.%j
#SBATCH --time=12:00:00
#SBATCH --partition={partition_with_gpus}
#SBATCH --gres=gpu:4

### change 5-digit MASTER_PORT as you wish, slurm will raise Error if duplicated with others
### change WORLD_SIZE as gpus/node * num_nodes
export MASTER_PORT=12340
export WORLD_SIZE=8

### get the first node name as master address
echo "NODELIST="${SLURM_NODELIST}
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
echo "MASTER_ADDR="$MASTER_ADDR


source path/to/python/venv/activate

srun python ../stylegan3/train.py --outdir=./training-runs-dist --cfg=stylegan3-t --data=path/to/training/data.zip --gpus=4 --batch=64 --gamma=8.2 --mirror=1
